// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/quizchamps/confirmation-email/:token": {
    params: {
      "token": string;
    };
  };
  "/send-confirmation-email/:id": {
    params: {
      "id": string;
    };
  };
  "/reset-password/:token": {
    params: {
      "token": string;
    };
  };
  "/verify-token/:token": {
    params: {
      "token": string;
    };
  };
  "/forgot-password": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/quizchamps/confirmation-email/:token" | "/send-confirmation-email/:id" | "/reset-password/:token" | "/verify-token/:token" | "/forgot-password" | "/sign-in" | "/sign-up";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "resource-routes/email/confirmation-token.$token.ts": {
    id: "resource-routes/email/confirmation-token.$token";
    page: "/quizchamps/confirmation-email/:token";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/send-confirmation-email/:id" | "/reset-password/:token" | "/verify-token/:token" | "/forgot-password" | "/sign-in" | "/sign-up" | "/";
  };
  "routes/_auth.send-confirmation-email.$id.tsx": {
    id: "routes/_auth.send-confirmation-email.$id";
    page: "/send-confirmation-email/:id";
  };
  "routes/_auth.reset-password.$token.tsx": {
    id: "routes/_auth.reset-password.$token";
    page: "/reset-password/:token";
  };
  "routes/_auth.verify-token.$token.tsx": {
    id: "routes/_auth.verify-token.$token";
    page: "/verify-token/:token";
  };
  "routes/_auth.forgot-password.tsx": {
    id: "routes/_auth.forgot-password";
    page: "/forgot-password";
  };
  "routes/_auth.sign-in.tsx": {
    id: "routes/_auth.sign-in";
    page: "/sign-in";
  };
  "routes/_auth.sign-up.tsx": {
    id: "routes/_auth.sign-up";
    page: "/sign-up";
  };
  "routes/_auth._index.tsx": {
    id: "routes/_auth._index";
    page: "/";
  };
};