// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/reset-password/:token": {
    params: {
      "token": string;
    };
  };
  "/auth/verify-token/:token": {
    params: {
      "token": string;
    };
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/sign-in": {
    params: {};
  };
  "/auth/sign-up": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/reset-password/:token" | "/auth/verify-token/:token" | "/auth/forgot-password" | "/auth/sign-in" | "/auth/sign-up";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth" | "/auth/reset-password/:token" | "/auth/verify-token/:token" | "/auth/forgot-password" | "/auth/sign-in" | "/auth/sign-up";
  };
  "routes/auth.reset-password.$token.tsx": {
    id: "routes/auth.reset-password.$token";
    page: "/auth/reset-password/:token";
  };
  "routes/auth.verify-token.$token.tsx": {
    id: "routes/auth.verify-token.$token";
    page: "/auth/verify-token/:token";
  };
  "routes/auth.forgot-password.tsx": {
    id: "routes/auth.forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/auth.sign-in.tsx": {
    id: "routes/auth.sign-in";
    page: "/auth/sign-in";
  };
  "routes/auth.sign-up.tsx": {
    id: "routes/auth.sign-up";
    page: "/auth/sign-up";
  };
  "routes/auth._index.tsx": {
    id: "routes/auth._index";
    page: "/auth";
  };
};