// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/send-confirmation-email": {
    params: {};
  };
  "/reset-password/:token": {
    params: {
      "token": string;
    };
  };
  "/verify-token/:token": {
    params: {
      "token": string;
    };
  };
  "/forgot-password": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/send-confirmation-email" | "/reset-password/:token" | "/verify-token/:token" | "/forgot-password" | "/sign-in" | "/sign-up";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/send-confirmation-email" | "/reset-password/:token" | "/verify-token/:token" | "/forgot-password" | "/sign-in" | "/sign-up" | "/";
  };
  "routes/_auth.send-confirmation-email.tsx": {
    id: "routes/_auth.send-confirmation-email";
    page: "/send-confirmation-email";
  };
  "routes/_auth.reset-password.$token.tsx": {
    id: "routes/_auth.reset-password.$token";
    page: "/reset-password/:token";
  };
  "routes/_auth.verify-token.$token.tsx": {
    id: "routes/_auth.verify-token.$token";
    page: "/verify-token/:token";
  };
  "routes/_auth.forgot-password.tsx": {
    id: "routes/_auth.forgot-password";
    page: "/forgot-password";
  };
  "routes/_auth.sign-in.tsx": {
    id: "routes/_auth.sign-in";
    page: "/sign-in";
  };
  "routes/_auth.sign-up.tsx": {
    id: "routes/_auth.sign-up";
    page: "/sign-up";
  };
  "routes/_auth._index.tsx": {
    id: "routes/_auth._index";
    page: "/";
  };
};